### ISSUE TITLE
Extend integerise to higher (>2) dimensions

### ISSUE THREAD

**Issue by virgesmith** [philmikejones/rakeR#44]
Since integerise only uses the total population constraint, it should be straightfoward to extend the function to accept arrays of arbitrary dimension

**Comment by philmikejones** [comment]
I'm not sure I want to implement this; the point of the functions is to take standard inputs (data frames) and produce a standard output (a data frame again).

Is there an example use-case where this would be beneficial, or that n-dimensional arrays can solve a problem a data frame input cannot?

**Comment by virgesmith** [comment]
No I don't have a use case. Cant remember what I was thinking/needing to solve at when I raised this now anyway. Closing.

**Comment by philmikejones** [comment]
No worries. If you suddenly recall something feel free to open again.
